name: build

on:
  push:
    tags:
    - 'v*'
    branches:
    - '**'
    pull_request:
      types: [opened, synchronize, reopened]

jobs:
  build-psp:
    name: Build PSP
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Build in Docker container
      uses: addnab/docker-run-action@v2
      with:
        options: --volume ${{ github.workspace }}:/woth --workdir /woth
        image: zie87/pspdev
        shell: bash
        run: | 
          ./tools/psp/psp_build_meson.sh ${{ matrix.build_type }}

  build-linux:
    name: Build Linux
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build_type: [debug, release]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: pip install meson ninja
    - run: |
        sudo apt update 
        sudo apt install git libsdl2-dev libpng-dev libjpeg-dev libfreetype-dev libz-dev libboost-all-dev 
    - name: Configure
      run: meson setup builddir/ --buildtype ${{ matrix.build_type }}
      env:
        CC: gcc-12
        CXX: g++-12
    - name: Compile
      run: meson compile -C builddir/ -v

  build-mingw32:
    name: Build MinGW (i686)
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Build in Docker container
      uses: addnab/docker-run-action@v2
      with:
        options: --volume ${{ github.workspace }}:/woth --workdir /woth
        image: zie87/mingw
        shell: bash
        run: | 
          ./tools/mingw/i686_build_meson.sh ${{ matrix.build_type }}

  build-mingw64:
    name: Build MinGW (x86_64)
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Build in Docker container
      uses: addnab/docker-run-action@v2
      with:
        options: --volume ${{ github.workspace }}:/woth --workdir /woth
        image: zie87/mingw
        shell: bash
        run: | 
          ./tools/mingw/x86_64_build_meson.sh ${{ matrix.build_type }}
