name: Build, publish
on:
  push: 
    tags:
    - 'v*'
    branches:
    - main
  
    pull_request:
      paths:
        - "**.cpp"
        - "**.hpp"

jobs:
  build-psp:
    name: Build PSP
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: 'recursive'
    - name: Build in Docker container
      uses: addnab/docker-run-action@v2
      with:
        options: --volume ${{ github.workspace }}:/woth --workdir /woth
        image: zie87/pspdev
        shell: bash
        run: | 
          ./tools/psp_build_meson.sh ${{ matrix.build_type }} 
